version: '2.1'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: 'canyan/janus-gateway:0.9.2'
    command:
      - "/usr/local/bin/janus"
      - "-P"
      - "/usr/local/lib/janus/plugins"
      - "-F"
      - "/usr/local/etc/janus"
      - "-n"
      - "janus-gateway"
      - "--event-handlers"
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: always