FROM golang:1.13.5-alpine3.10 as builder
RUN apk update && apk upgrade && \
    apk add \
    xz-dev \
    musl-dev \
    gcc
RUN mkdir -p /go/src/github.com/canyanio/rating-agent-janus
COPY . /go/src/github.com/canyanio/rating-agent-janus
RUN cd /go/src/github.com/canyanio/rating-agent-janus && \
    env CGO_ENABLED=0 go test -c -o rating-agent-janus-test -coverpkg $(go list ./... | grep -v vendor | grep -v mocks | grep -v test | tr  '\n' ,)

FROM alpine:3.10
RUN apk update && apk upgrade && \
        apk add --no-cache ca-certificates xz
RUN mkdir -p /etc/rating-agent-janus
COPY ./config.yaml /etc/rating-agent-janus
COPY --from=builder /go/src/github.com/canyanio/rating-agent-janus/rating-agent-janus-test /usr/bin
ENTRYPOINT [ \
    "/usr/bin/rating-agent-janus-test", \
    "-test.coverprofile=/src/coverage-acceptance.txt", \
    "-acceptance-tests", \
    "-test.run=TestRunMain", \
    "-cli-args=--config=/etc/rating-agent-janus/config.yaml --debug agent" \
]

EXPOSE 9060/udp
