version: '2.1'
services:

  #
  # The Janus agent
  #
  rating-agent-janus:
    image: 'canyan/rating-agent-janus:master'
    environment:
    - RATING_AGENT_JANUS_MESSAGE_BUS_URI=amqp://user:password@rabbitmq:5672//
    - RATING_AGENT_JANUS_REDIS_ADDRESS=redis:6379
    volumes:
      - "./:/src/"
    depends_on:
    - rabbitmq
    - redis
    restart: always
